[package]
name = "uastar"
version = "0.1.0"
authors = ["Edoardo Morandi <morandidodo@gmail.com>"]
edition = "2018"
license = "Zlib"

[dependencies]
libc = "0.2.67"

[dev-dependencies]
rand = { version = "0.7.3", features = [ "small_rng" ] }
once_cell = "1.3.1"
